### ISSUE TITLE
Clang-Format格式化代码 - Dominic

### ISSUE THREAD

**Issue by Dunky-Z** [Dunky-Z/comment#3]
https://dunky-z.github.io/2021/12/01/Clang-Format%E6%A0%BC%E5%BC%8F%E5%8C%96%E4%BB%A3%E7%A0%81/

**Comment by liangshenlin** [comment]
giao

**Comment by GeorgyKwe** [comment]
diao

**Comment by liangshenlin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liangshenlin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
